version: "3"
services: 
  meraki-webhook:
    build: .
    container_name: meraki-webhook
    restart: always
    volumes:
      - ./webhooks.log:/app/webhooks.log

      networks:
        - proxynet
  
  networks:
    proxynet:
      external:
        name: proxy_sites
  