version: "3"
services: 
  meraki-webhook:
    build: .
    container_name: meraki-webhook
    restart: always
    volumes:
      - ./logs:/app/logs

    networks:
      - proxynet


networks:
  proxynet:
    external:
      name: proxy_sites
  